language: c
os: linux

bracnhes:
  only:
  - master

compiler:
    - clang

matrix:
  include:
      # works on Trusty
    - os: linux
      addons:
          apt:
              sources:
                  - llvm-toolchain-trusty-5.0
              packages:
                  - clang-5.0
              env:
                  - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
   - echo "Before Install prerequite"

install:
    echo "Installing prerequite"

before_script:
    - echo "before script " `pwd`

script:
   - echo "building..."
   - make

before_cache:
    echo "before cache"

after_success:
    - echo "after success"
    - ./mshell < test
    - gcov bash.c 
    - bash <(curl -s https://codecov.io/bash)

after_failure:
    echo "after failure"

before_deploy:
    echo "before deploy"

deploy:
  - provider: script
    script:
        echo "deploying "
    on:
      branch: master

after_deploy:
    echo " after deploy"

after_script:
    echo " after script"
