language: c
os: linux

bracnhes:
  only:
  - master

compiler:
    - gcc

env:
    global:
        - CODECOV_TOKEN="49b7243b-7efa-423f-ac5b-01a5010e5cf7"

before_install:
    echo "Before Install prerequite"

install:
    echo "Installing prerequite"

before_script:
    echo "before script"

script:
    echo "building..."
    make

before_cache:
    echo "before cache"

after_success:
    - echo "after success"
    - ./mshell < test
    - gcov bash.c 
    - bash <(curl -s https://codecov.io/bash)

after_failure:
    echo "after failure"

before_deploy:
    echo "before deploy"

deploy:
  - provider: script
    script:
        echo "deploying "
    on:
      branch: master

after_deploy:
    echo " after deploy"

after_script:
    echo " after script"

