language: c
os: linux

bracnhes:
  only:
  - master

compiler:
    - clang

python: 3.7

before_install:
   - echo "Before Install prerequite"
   - pip3 install coveragepy

install:
    echo "Installing prerequite"

before_script:
    - echo "before script " `pwd`


script:
   - echo "building..."
   - make

before_cache:
    echo "before cache"

after_success:
    - echo "after success"
    - ./mshell < test
    - gcov bash.c 
    - bash <(curl -s https://codecov.io/bash)

after_failure:
    echo "after failure"

before_deploy:
    echo "before deploy"

deploy:
  - provider: script
    script:
        echo "deploying "
    on:
      branch: master

after_deploy:
    echo " after deploy"

after_script:
    echo " after script"

