language: c
os: linux

bracnhes:
  only:
  - master
        

compiler:
    - gcc

before_install:
    echo "Before Install prerequite"
    pip install --user cpp-coveralls

install:
    echo "Installing prerequite"

before_script:
    echo "before script"

script:
    echo "building..."
    make

before_cache:
    echo "before cache"

after_success:
    echo "after success"
    ./bash < test
    coveralls --exclude lib --exclude tests --gcov-options '\-lp'

after_failure:
    echo "after failure"

before_deploy:
    echo "before deploy"

deploy:
  - provider: script
    script:
        echo "deploying "
    on:
      branch: master

after_deploy:
    echo " after deploy"

after_script:
    echo " after script"
